version: "3.7"
networks:
  eshop-net:
    driver: bridge

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD.txt

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./..
    container_name: eshop_app
    volumes:
      - ~/oauthkeys:/app/oauthkeys
    ports:
      - "6060:80"
    networks:
      - eshop-net

  database:
    image: postgres:latest
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=eshop
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=eshop
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5464:5432
    networks:
      - eshop-net

  database_log:
    image: postgres:latest
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=eshop_log
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=eshop_log
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5465:5432
    networks:
      - eshop-net

volumes:
  cache:
    driver: local
  kafka:
    driver: local
  app:
    driver: local
  db:
    driver: local