version: "3.7"
networks:
  eshop-net:
    driver: bridge

secrets:
  POSTGRES_PASSWORD:
    file: ./secrets/POSTGRES_PASSWORD.txt
  REDIS_PASSWORD:
    file: ./secrets/REDIS_PASSWORD.txt

services:
  database:
    image: postgres:latest
    container_name: eshop_db
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=eshop
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=eshop
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5464:5432
    networks:
      - eshop-net

  database_log:
    image: postgres:latest
    container_name: eshop_log_db
    restart: always
    secrets:
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER=eshop_log
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=eshop_log
    volumes:
      - dblog:/var/lib/postgresql/data
    ports:
      - 5465:5432
    networks:
      - eshop-net

  app:
    build:
      dockerfile: Dockerfile-dev
      context: ./..
    container_name: eshop_app
    ports:
      - "8080:8080"
    depends_on:
      - database
      - database_log
    restart: always
    networks:
      - eshop-net

volumes:
  cache:
    driver: local
  db:
    driver: local
  dblog:
    driver: local