FROM golang:1.20

RUN mkdir -p /build
RUN mkdir -p /app
# RUN mkdir -p /uploads

ADD . /build/
# ADD ./uploads /uploads/

WORKDIR /build
RUN go mod vendor
RUN CGO_ENABLED=0 GOOS=linux go build -buildvcs=false -o /app/main .

RUN rm -rf /build

WORKDIR /app
ADD ./uploads ./uploads/
COPY ./oauth-keys ./oauth-keys
COPY ./config.docker.toml ./config.toml

EXPOSE 8080

ENTRYPOINT ["/app/main"]
CMD ["serve"]